name: "web_app"
mode: "release"
port: "8081"
start_time: "2022-08-01"
machine_id: 1
log:
  level: "debug"
  filename: "web_app.log"
  max_backups: 7
  max_age: 30
  max_size: 20
mysql:
  host: "127.0.0.1"
  port: 3306
  user: "root"
  password: "root"
  dbname: "bluebell"
  max_size: 200
  max_idle: 30
redis:
  host: "127.0.0.1"
  port: 6379
  password: ""
  db: 0
  pool_size: 10